@echo off
mkdir "00_Sandbox\ICONS"
type nul > "00_Sandbox\ICONS\temp.txt"
mkdir "00_Sandbox\PROGRESS"
type nul > "00_Sandbox\PROGRESS\temp.txt"
mkdir "00_Sandbox\USER_name"
type nul > "00_Sandbox\USER_name\temp.txt"
mkdir "01_Preproduction\Concept\00_Moodboards"
type nul > "01_Preproduction\Concept\00_Moodboards\temp.txt"
mkdir "01_Preproduction\Concept\01_Mindmaps"
type nul > "01_Preproduction\Concept\01_Mindmaps\temp.txt"
mkdir "01_Preproduction\Concept\02_Design-Sheets"
type nul > "01_Preproduction\Concept\02_Design-Sheets\temp.txt"
mkdir "01_Preproduction\Documents\CONTRACTS"
type nul > "01_Preproduction\Documents\CONTRACTS\temp.txt"
mkdir "01_Preproduction\Documents\FORMAL"
type nul > "01_Preproduction\Documents\FORMAL\temp.txt"
mkdir "01_Preproduction\Documents\IDEAS"
type nul > "01_Preproduction\Documents\IDEAS\temp.txt"
mkdir "01_Preproduction\Documents\WORKSHEETS"
type nul > "01_Preproduction\Documents\WORKSHEETS\temp.txt"
mkdir "01_Preproduction\PROJECT_Name\00_Brief"
type nul > "01_Preproduction\PROJECT_Name\00_Brief\temp.txt"
mkdir "01_Preproduction\PROJECT_Name\01_Story"
type nul > "01_Preproduction\PROJECT_Name\01_Story\temp.txt"
mkdir "01_Preproduction\PROJECT_Name\02_Shotscript"
type nul > "01_Preproduction\PROJECT_Name\02_Shotscript\temp.txt"
mkdir "01_Preproduction\PROJECT_Name\03_World"
type nul > "01_Preproduction\PROJECT_Name\03_World\temp.txt"
type nul > "01_Preproduction\PROJECT_Name\temp.txt"
mkdir "02_Input\Models"
type nul > "02_Input\Models\temp.txt"
mkdir "02_Input\Sources"
type nul > "02_Input\Sources\temp.txt"
mkdir "02_Input\Textures"
type nul > "02_Input\Textures\temp.txt"
mkdir "02_Input\Videos"
type nul > "02_Input\Videos\temp.txt"
mkdir "04_Production\01_Assets\Characters\Char_Name\00_PUBLISH"
type nul > "04_Production\01_Assets\Characters\Char_Name\00_PUBLISH\temp.txt"
mkdir "04_Production\01_Assets\Characters\Char_Name\01_Input"
type nul > "04_Production\01_Assets\Characters\Char_Name\01_Input\temp.txt"
mkdir "04_Production\01_Assets\Characters\Char_Name\02_Modeling"
type nul > "04_Production\01_Assets\Characters\Char_Name\02_Modeling\temp.txt"
mkdir "04_Production\01_Assets\Characters\Char_Name\03_Lookdev"
type nul > "04_Production\01_Assets\Characters\Char_Name\03_Lookdev\temp.txt"
mkdir "04_Production\01_Assets\Characters\Char_Name\04_Rigging"
type nul > "04_Production\01_Assets\Characters\Char_Name\04_Rigging\temp.txt"
type nul > "04_Production\01_Assets\Characters\Char_Name\Textures\temp.txt"
type nul > "04_Production\01_Assets\Characters\Char_Name\temp.txt"
type nul > "04_Production\01_Assets\Characters\desktop.ini"
mkdir "04_Production\01_Assets\Libraries\Compositor"
type nul > "04_Production\01_Assets\Libraries\Compositor\temp.txt"
mkdir "04_Production\01_Assets\Libraries\Geometry Nodes"
type nul > "04_Production\01_Assets\Libraries\Geometry Nodes\temp.txt"
mkdir "04_Production\01_Assets\Libraries\Rigs"
type nul > "04_Production\01_Assets\Libraries\Rigs\temp.txt"
mkdir "04_Production\01_Assets\Libraries\Shaders"
type nul > "04_Production\01_Assets\Libraries\Shaders\temp.txt"
type nul > "04_Production\01_Assets\Libraries\temp.txt"
mkdir "04_Production\01_Assets\Props\Prop_PropName\00_PUBLISH"
type nul > "04_Production\01_Assets\Props\Prop_PropName\00_PUBLISH\temp.txt"
mkdir "04_Production\01_Assets\Props\Prop_PropName\01_Input"
type nul > "04_Production\01_Assets\Props\Prop_PropName\01_Input\temp.txt"
mkdir "04_Production\01_Assets\Props\Prop_PropName\02_Modeling"
type nul > "04_Production\01_Assets\Props\Prop_PropName\02_Modeling\temp.txt"
mkdir "04_Production\01_Assets\Props\Prop_PropName\03_Lookdev"
type nul > "04_Production\01_Assets\Props\Prop_PropName\03_Lookdev\temp.txt"
mkdir "04_Production\01_Assets\Props\Prop_PropName\04_Rigging"
type nul > "04_Production\01_Assets\Props\Prop_PropName\04_Rigging\temp.txt"
type nul > "04_Production\01_Assets\Props\Prop_PropName\Textures\temp.txt"
type nul > "04_Production\01_Assets\Readme.txt"
mkdir "04_Production\01_Assets\Scripts\ADDONS"
type nul > "04_Production\01_Assets\Scripts\ADDONS\temp.txt"
mkdir "04_Production\01_Assets\Scripts\COMPOSITE"
type nul > "04_Production\01_Assets\Scripts\COMPOSITE\temp.txt"
mkdir "04_Production\01_Assets\Scripts\RENDER"
type nul > "04_Production\01_Assets\Scripts\RENDER\temp.txt"
mkdir "04_Production\01_Assets\Scripts\RIGGING"
type nul > "04_Production\01_Assets\Scripts\RIGGING\temp.txt"
mkdir "04_Production\01_Assets\Scripts\SOFTWARE"
type nul > "04_Production\01_Assets\Scripts\SOFTWARE\temp.txt"
mkdir "04_Production\01_Assets\Textures\Texture_Name"
type nul > "04_Production\01_Assets\Textures\Texture_Name\temp.txt"
mkdir "04_Production\01_Assets\VFX\VFX_FXName"
type nul > "04_Production\01_Assets\VFX\VFX_FXName\temp.txt"
mkdir "04_Production\03_Sets\Set_Name\00_PUBLISH"
type nul > "04_Production\03_Sets\Set_Name\00_PUBLISH\temp.txt"
mkdir "04_Production\03_Sets\Set_Name\01_Input"
type nul > "04_Production\03_Sets\Set_Name\01_Input\temp.txt"
mkdir "04_Production\03_Sets\Set_Name\02_Modeling"
type nul > "04_Production\03_Sets\Set_Name\02_Modeling\temp.txt"
mkdir "04_Production\03_Sets\Set_Name\03_Lookdev"
type nul > "04_Production\03_Sets\Set_Name\03_Lookdev\temp.txt"
mkdir "04_Production\03_Sets\Set_Name\04_Rigging"
type nul > "04_Production\03_Sets\Set_Name\04_Rigging\temp.txt"
type nul > "04_Production\03_Sets\Set_Name\Textures\temp.txt"
type nul > "04_Production\03_Sets\Set_Name\temp.txt"
mkdir "04_Production\PROJECT_Name\01_PreProd"
type nul > "04_Production\PROJECT_Name\01_PreProd\temp.txt"
mkdir "04_Production\PROJECT_Name\02_Shots\S000\01_Input\A_ClipName_Frame-Range"
type nul > "04_Production\PROJECT_Name\02_Shots\S000\01_Input\A_ClipName_Frame-Range\temp.txt"
mkdir "04_Production\PROJECT_Name\02_Shots\S000\01_Input\B_ClipName_Frame-Range"
type nul > "04_Production\PROJECT_Name\02_Shots\S000\01_Input\B_ClipName_Frame-Range\temp.txt"
mkdir "04_Production\PROJECT_Name\02_Shots\S000\02_Previz"
type nul > "04_Production\PROJECT_Name\02_Shots\S000\02_Previz\temp.txt"
mkdir "04_Production\PROJECT_Name\02_Shots\S000\03_Anim"
type nul > "04_Production\PROJECT_Name\02_Shots\S000\03_Anim\temp.txt"
mkdir "04_Production\PROJECT_Name\02_Shots\S000\04_Fx"
type nul > "04_Production\PROJECT_Name\02_Shots\S000\04_Fx\temp.txt"
mkdir "04_Production\PROJECT_Name\02_Shots\S000\05_Assembly"
type nul > "04_Production\PROJECT_Name\02_Shots\S000\05_Assembly\temp.txt"
mkdir "04_Production\PROJECT_Name\02_Shots\S000\06_Light"
type nul > "04_Production\PROJECT_Name\02_Shots\S000\06_Light\temp.txt"
mkdir "04_Production\PROJECT_Name\02_Shots\S000\07_PUBLISH"
type nul > "04_Production\PROJECT_Name\02_Shots\S000\07_PUBLISH\temp.txt"
mkdir "04_Production\PROJECT_Name\02_Shots\S000\08_Render"
type nul > "04_Production\PROJECT_Name\02_Shots\S000\08_Render\temp.txt"
mkdir "04_Production\PROJECT_Name\02_Shots\S000\09_Comp"
type nul > "04_Production\PROJECT_Name\02_Shots\S000\09_Comp\temp.txt"
mkdir "04_Production\PROJECT_Name\02_Shots\S000\10_Export"
type nul > "04_Production\PROJECT_Name\02_Shots\S000\10_Export\temp.txt"
mkdir "05_Postproduction\01_Audio"
type nul > "05_Postproduction\01_Audio\temp.txt"
mkdir "05_Postproduction\PROJECT_Name\01_Sources\Project_Name"
type nul > "05_Postproduction\PROJECT_Name\01_Sources\Project_Name\temp.txt"
mkdir "05_Postproduction\PROJECT_Name\02_Sound"
type nul > "05_Postproduction\PROJECT_Name\02_Sound\temp.txt"
mkdir "05_Postproduction\PROJECT_Name\03_Edit\Project_Name"
type nul > "05_Postproduction\PROJECT_Name\03_Edit\Project_Name\temp.txt"
mkdir "UE4\Content\Art\Blueprints"
type nul > "UE4\Content\Art\Blueprints\temp.txt"
mkdir "UE4\Content\Art\Materials"
type nul > "UE4\Content\Art\Materials\temp.txt"
mkdir "UE4\Content\Art\Static-Meshes"
type nul > "UE4\Content\Art\Static-Meshes\temp.txt"
mkdir "UE4\Content\Art\Textures"
type nul > "UE4\Content\Art\Textures\temp.txt"
mkdir "UE4\Content\Art"
type nul > "UE4\Content\Art\temp.txt"
mkdir "UE4\Content\Maps"
type nul > "UE4\Content\Maps\temp.txt"
mkdir "UE4\Content"
type nul > "UE4\Content\temp.txt"
mkdir "UE4\Plugins"
type nul > "UE4\Plugins\temp.txt"